package hu.uni.miskolc.tezsteles.core;

public enum Valto {
	MANUALIS_6_FOKOZAT, MANUALIS_5_FOKOZAT, AUTOMATA, MANUALIS_4, MANUALIS_12, MANUALIS_18, NINCS, 
	SZEKVENCIALIS, DSG, PILLANGO, VEGYES;

    public enum Uzemanyag {
        BENZIN, DIESEL, ELEKTROMOS, HYBRID, KEROZIN, VIZ, HIDROGEN, FLINTSTONES, LPG
    }
}
